name: social_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  conditional_builder_null_safety: ^0.0.6
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  font_awesome_flutter: ^9.2.0
  flex_color_scheme: ^4.1.1  
  google_fonts: ^2.2.0  
  dio: ^4.0.4
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.4
  firebase_messaging: ^11.2.5
  intl: ^0.17.0
  equatable: 
  tuple:
  shimmer: ^2.0.0 






  
dev_dependencies:
 
  flutter_test:
    sdk: flutter

  flutter_native_splash: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/appicon.png"

flutter_native_splash:
  color: "#f1faee"
  image: "assets/images/appicon.png"





flutter:


  uses-material-design: true


  assets:
    - assets/images/
